# Site settings
author: David Bartholomew
title: Being A Data Science Student
header-img: img/home-bg.png
email: dbarth411@gmail.com
copyright_name: David Bartholomew
description: > # this means to ignore newlines until "baseurl:"
  Learning data science like nobody's business
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: dbarth411
github_username:  dbarth411

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
